version: '3.8'

services:
  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # Backend development server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/srtgo_web.db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=dev-secret-key-not-for-production
      - DEBUG=true
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery worker for development
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/srtgo_web.db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=dev-secret-key-not-for-production
    depends_on:
      - redis
      - backend
    command: celery -A app.tasks.celery_app worker --loglevel=info

volumes:
  redis_dev_data:
  backend_dev_data: